# Default values for cas-gateway.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: adamcharnock/python-cas-gateway
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: nginx
  type: ClusterIP
  externalPort: 80
  internalPort: 80

backendUrl: ''
casUrl: ''
timeout: 10
casVersion: '3'
chunkSize: 4096
